EzGeoDataGouv_content_view:
  path: /ez_geo_data_gouv/view/content/{contentId}/{viewType}/{distance}
  defaults:
    _controller: ez_content:viewAction
    viewType: line
    locationId: null
    layout: false
    distance: 0
  options:
    expose: true
