services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  eZGeoDataGouv\Config\ConfigManager:

  eZGeoDataGouv\DataFlowType\DataGouvImportLocationsDataFlowType:
    tags:
      - { name: coderhapsodie.dataflow.type }

  eZGeoDataGouv\DataFlow\FileReader:

  eZGeoDataGouv\DataFlow\GeocodingFileReader:

  eZGeoDataGouvBundle\Rest\DefaultController:
    autoconfigure: false
    autowire: true
    parent: Ibexa\Rest\Server\Controller

  ez_geo_data_gouv.rest.controller:
    alias: eZGeoDataGouvBundle\Rest\DefaultController

  ez_geo_data_gouv.rest.value_object_visitor.LocationContent:
    autoconfigure: false
    autowire: false
    public: true
    parent: Ibexa\Contracts\Rest\Output\ValueObjectVisitor
    class: eZGeoDataGouvBundle\Rest\ValueObjectVisitor\LocationContent
    arguments: ['@Ibexa\Core\Helper\TranslationHelper']
    tags:
      - { name: ibexa.rest.output.value_object.visitor, type: eZGeoDataGouvBundle\Rest\Values\LocationContent }

  ez_geo_data_gouv.event.subscriber.view_builder:
    class: eZGeoDataGouvBundle\EventSubscriber\ViewBuilderSubscriber
    tags:
      - {name: kernel.event_subscriber}

  ez_geo_data_gouv.data_flow.ez_matrix_field_value_creator:
    class: eZGeoDataGouv\DataFlow\Field\EzMatrixFieldValueCreator
    tags:
      - { name: 'coderhapsodie.ezdataflow.field_value_creator' }

