services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  eZGeoDataGouv\DataFlowType\DataGouvImportLocationsDataFlowType:
    arguments:
      $config: '%ez_geo_data_gouv.resources%'
    tags:
      - { name: coderhapsodie.dataflow.type }

  eZGeoDataGouv\DataFlow\FileReader:

  eZGeoDataGouv\DataFlow\GeocodingFileReader:
    arguments:
      $api_url: '%ez_geo_data_gouv.api_url%'

  eZGeoDataGouvBundle\Rest\DefaultController:
    autoconfigure: false
    autowire: false
    public: true
    parent: 'ezpublish_rest.controller.base'

  ez_geo_data_gouv.rest.controller:
    alias: eZGeoDataGouvBundle\Rest\DefaultController
    public: true