services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  eZGeoDataGouv\DataFlowType\DataGouvImportLocationsDataFlowType:
    tags:
      - { name: coderhapsodie.dataflow.type }